development:
  adapter: postgresql
  encoding: unicode
  database: postlogdb
  pool: 5
  username: vagrant
  password: qwerty

test:
  adapter: postgresql
  encoding: unicode
  database: postlogdb
  pool: 5
  username: vagrant
  password: qwerty

production:
  adapter: postgresql
  encoding: unicode
  database: postlogdb
  pool: 5
